include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    only_throw_errors: false
    avoid_dynamic_calls: false
    lines_longer_than_80_chars: false
    # always_use_package_imports: false