name: ultimate_bundle
description: A new Flutter project.
publish_to: 'none'
version: 1.6.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  awesome_card: ^1.1.5
  bottom_navy_bar: ^6.0.0
  bottom_sheet: ^1.0.1
  buttons_tabbar: ^1.3.1
  cached_network_image: ^3.1.0
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_star: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_swiper_null_safety: ^1.0.2
  fluttertoast: ^8.0.8
  form_field_validator: ^1.1.0
  get: ^4.3.8
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+2
  launch_review: ^3.0.1
  octo_image: ^1.0.0+1
  photo_view: ^0.12.0
  pin_code_fields: ^7.3.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  responsive_grid: ^2.0.0
  share: ^2.0.4
  simple_animations: ^3.1.1
  smooth_star_rating:
    git:
      url: https://github.com/educup/smoothratingbar
  timeago: ^3.1.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.11
  very_good_analysis: ^2.3.0
  firebase_core:
  cloud_firestore:
  firebase_auth:
  otp_text_field:
  pinch_zoom: ^1.0.0
  flutterfire_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
