import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:get/get.dart';
import 'package:ultimate_bundle/helpers/constants.dart';
import 'package:ultimate_bundle/src/shuppy/helpers/constants.dart';
import 'package:ultimate_bundle/src/shuppy/helpers/local_data.dart';
import 'package:ultimate_bundle/src/shuppy/helpers/snack_toast.dart';
import 'package:ultimate_bundle/src/shuppy/models/arguments_model.dart';
import 'package:ultimate_bundle/src/shuppy/models/product_model.dart';
import 'package:ultimate_bundle/src/shuppy/pages/home/home_page.dart';
import 'package:ultimate_bundle/src/shuppy/widgets/custom_app_bar.dart';
import 'package:ultimate_bundle/src/shuppy/widgets/custom_elevated_button.dart';
import 'package:ultimate_bundle/src/shuppy/widgets/custom_price_text.dart';
import 'package:ultimate_bundle/src/shuppy/widgets/custom_shake_transtition.dart';
import 'package:ultimate_bundle/src/shuppy/widgets/empty_section.dart';
import 'package:intl/intl.dart';

part 'screens/cart_screen.dart';
part 'widgets/build_cart_item.dart';
part 'widgets/build_cart_card.dart';
part 'widgets/body_section.dart';
